# Generated by Django 2.2.3 on 2020-08-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20200731_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': '项目信息表', 'verbose_name_plural': '项目信息表'},
        ),
        migrations.AlterModelOptions(
            name='servertype',
            options={'verbose_name': '项目类型表', 'verbose_name_plural': '项目类型表'},
        ),
        migrations.AlterField(
            model_name='server',
            name='brand',
            field=models.CharField(blank=True, max_length=50, verbose_name='开发令号'),
        ),
        migrations.AlterField(
            model_name='server',
            name='description',
            field=models.CharField(blank=True, max_length=50, verbose_name='项目概述'),
        ),
        migrations.AlterField(
            model_name='server',
            name='guartime',
            field=models.CharField(blank=True, max_length=50, verbose_name='项目级别'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ipaddress',
            field=models.CharField(blank=True, max_length=100, verbose_name='项目名'),
        ),
        migrations.AlterField(
            model_name='server',
            name='undernet',
            field=models.CharField(max_length=10, verbose_name='延期风险'),
        ),
        migrations.AlterField(
            model_name='server',
            name='zcmodel',
            field=models.CharField(blank=True, max_length=50, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='server',
            name='zcnumber',
            field=models.CharField(blank=True, max_length=50, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='server',
            name='zcpz',
            field=models.CharField(blank=True, max_length=100, verbose_name='项目现状'),
        ),
        migrations.AlterField(
            model_name='serverhis',
            name='brand',
            field=models.CharField(blank=True, max_length=50, verbose_name='开发令号'),
        ),
        migrations.AlterField(
            model_name='serverhis',
            name='description',
            field=models.CharField(blank=True, max_length=50, verbose_name='项目概述'),
        ),
        migrations.AlterField(
            model_name='serverhis',
            name='guartime',
            field=models.CharField(blank=True, max_length=10, verbose_name='项目等级'),
        ),
        migrations.AlterField(
            model_name='serverhis',
            name='ipaddress',
            field=models.CharField(blank=True, max_length=100, verbose_name='项目名'),
        ),
        migrations.AlterField(
            model_name='serverhis',
            name='owner',
            field=models.CharField(max_length=20, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='serverhis',
            name='serverid',
            field=models.IntegerField(verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='serverhis',
            name='undernet',
            field=models.CharField(max_length=10, verbose_name='延期风险'),
        ),
        migrations.AlterField(
            model_name='serverhis',
            name='zcmodel',
            field=models.CharField(blank=True, max_length=50, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='serverhis',
            name='zcnumber',
            field=models.CharField(blank=True, max_length=50, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='serverhis',
            name='zcpz',
            field=models.CharField(blank=True, max_length=100, verbose_name='项目现状'),
        ),
        migrations.AlterField(
            model_name='serverhis',
            name='zctype',
            field=models.CharField(max_length=20, verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='servertype',
            name='zctype',
            field=models.CharField(max_length=20, verbose_name='项目类型'),
        ),
    ]
