# Generated by Django 2.2.3 on 2020-08-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20200801_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='warn_times',
            field=models.IntegerField(default=0, verbose_name='项目预警次数'),
        ),
    ]
